Issue#1310: Add consistent case rules for paramter names in subprograms.
jeremiah-c-leary/vhdl-style-guide pull request #1311
Opened 2024-11-10 02:05 UTC by JHertz5

Resolves #1310.
Currently still a work in progress - see #1254 for details.

2024-12-17 21:18 UTC, jeremiah-c-leary requested changes

2024-12-17 21:18 UTC, jeremiah-c-leary commented on tests/procedure/rule_509_test_input.fixed.vhd
> +      constant con : integer := param1;
Is the scope of `param1` correct?  It would seem is should be scoped to the function at line 162 instead of the procedure at line 139.

2024-12-17 21:18 UTC, jeremiah-c-leary commented on tests/procedure/rule_509_test_input.fixed.vhd
> +      var := param1 when true else Param2;
I think `param1` should not have been changed since it is local to the function `my_func`.  I noticed the function does not include a `param1` argument though.

2024-12-18 09:21 UTC, JHertz5 commented on tests/procedure/rule_509_test_input.fixed.vhd
> +      constant con : integer := param1;
That's a good point! This function needs to be declared `impure` to access `param1` from the parent subprogram, otherwise the code is invalid. I'll update the file.

2024-12-18 09:21 UTC, JHertz5 commented on tests/procedure/rule_509_test_input.fixed.vhd
> +      var := param1 when true else Param2;
`param1` is not declared within `my_func` (either as a parameter or as a variable/constant), so I don't think that it can be local to here. Since `param1` is not declared within `my_func`, I believe that the `param1` from the parameter list of the parent subprogram will be used. I've added the `impure` keyword to `my_func` to make sure that the code is valid.

2024-12-18 09:22 UTC, JHertz5 commented
Thanks for your feedback @jeremiah-c-leary. I've actioned your comments and left some responses. The PR is ready for you to look at again.

2024-12-20 00:58 UTC, jeremiah-c-leary commented on tests/procedure/rule_509_test_input.fixed.vhd
> +      var := param1 when true else Param2;
Evening @JHertz5 ,

Clearly I have never used an impure function.  I did read the LRM about pure and impure functions and agree with the case change as you have it shown.

It just seems you would want to always use a pure function.

--Jeremy

2024-12-20 01:20 UTC, jeremiah-c-leary approved these changes

2024-12-20 01:28 UTC, merged

2024-12-20 09:09 UTC, JHertz5 commented on tests/procedure/rule_509_test_input.fixed.vhd
> +      var := param1 when true else Param2;
Hi @jeremiah-c-leary

Yes, I've never come across a time where I've needed to use an impure function. I'd have thought that it would be undesirable for functions to have undeclared side-effects, but I suppose someone out there must have a use case for them to have included it in the language.

Thanks,
Jukka