Issue#1364: Case rules for subprogram instantiations.
jeremiah-c-leary/vhdl-style-guide pull request #1371
Opened 2024-12-22 02:29 UTC by JHertz5

Resolves #1364.
Note that, as part of this work, I discovered that function_014 and procedure_505 are programmed to act on all instances of their respective subprogram kind, which meant that, contrary to their description, they were acting on subprogram instantiations. I've deprecated those rules and replaced them with `subprogram_kind` rules. If this approach is not preferred, I am happy to revert/modify those changes.

2024-12-31 22:30 UTC, jeremiah-c-leary requested changes
Evening @JHertz5 ,

The PR looks good.  I agree with creating the subprogram_kind rules and deprecating function_014 and procedure_505.

I just had a couple of questions on the rule documentation.

Thanks again,

--Jeremy

2024-12-31 22:30 UTC, jeremiah-c-leary commented on docs/subprogram_kind_rules.rst
> +   PROCEDURE my_proc is new my_generic_proc
Should PROCEDURE be changed to lower case on lines 27 and 29?

2024-12-31 22:30 UTC, jeremiah-c-leary commented on docs/subprogram_kind_rules.rst
> +   FUNCTION my_func is new my_generic_func
Should FUNCTION be changed to lowercase on lines 52 and 54?

2025-01-01 13:57 UTC, JHertz5 commented on docs/subprogram_kind_rules.rst
> +   PROCEDURE my_proc is new my_generic_proc
You are absolutely right, thanks for catching that!

2025-01-01 13:57 UTC, JHertz5 commented on docs/subprogram_kind_rules.rst
> +   FUNCTION my_func is new my_generic_func
You are absolutely right, thanks for catching that!

2025-01-01 13:57 UTC, JHertz5 commented
Hi @jeremiah-c-leary

> I just had a couple of questions on the rule documentation.

Thanks for catching those mistakes! I've made corrections and the PR is ready for you to look at again.

Thanks,
Jukka

2025-01-01 17:39 UTC, jeremiah-c-leary approved these changes
Updates looks good.

2025-01-01 17:40 UTC, merged